name = "logicalmechanism/perma-lock"
version = "1.2.0"
license = "GPL-3.0-or-later"
description = "Permanently lock tokens"

[repository]
user = "logicalmechanism"
project = "perma-lock"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "v0.4.10"
source = "github"